### ISSUE TITLE
error

### ISSUE THREAD

**Issue by HashCat568** [scripted-1337/Discord-Mass-Mention#6]
(?) Guild ID: 949573948801163274
(?) Channel ID: 954629301704196186
(?) Proxytype: none
(?) Amount to spam: 10
(?) Threads/Tasks/Pools: 5000

Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x00000272F3262E90>>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\gateway.py", line 300, in _response_loop
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x00000272F3262E90>>
Traceback (most recent call last):
    function(resp, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\gateway.py", line 300, in _response_loop
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\guild\combo.py", line 71, in fetchMembers   
    function(resp, **params)
self.gatewayobj.session.guild(guild_id).resetMembers() #reset  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\guild\combo.py", line 89, in fetchMembers

      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\session.py", line 246, in resetMembers  
    ranges = self.getRanges(index, multiplier, self.gatewayobj.session.guild(guild_id).memberCount) if not endFetching else [[0],[0]]
Session.settings_ready['guilds'][self.guildID]['members'] = {}
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\session.py", line 376, in memberCount       
KeyError    return Session.settings_ready['guilds'][self.guildID]['member_count']:
'949573948801163274'
KeyError: '949573948801163274'

**Comment by scripted-1337** [comment]
`proxytype: none`
thats the problem
and if it isnt then discum problem
